#!/bin/bash

source config

if test $# -ne 1; then
    echo "Usage: $0 <firmware-identifier>" 1>&2
    echo "" 1>&2
    echo "Argument is firmware identifier (e.g iPhone5,1_9.3_13E237)" 1>&2
    exit 1
fi

firmware_id="$1"

ipsw="$IPSW_STORE"/"$firmware_id"_Restore.ipsw

out_dir="$OUT_STORE"/"$firmware_id"
decrypted="$out_dir"/decrypted.dmg
rootfs_img="$out_dir"/rootfs.img
fs_archive="$out_dir"/fs.tar.gz
sandboxd="$out_dir"/sandboxd
dyld_shared_cache="$out_dir"/dyld_shared_cache
kernelcache_decrypted="$out_dir"/kernelcache.decrypted
kernelcache="$out_dir"/kernelcache.mach.arm
sandbox_kext="$out_dir"/com.apple.security.sandbox.kext
sb_ops="$out_dir"/sb_ops
sandbox_profiles="$out_dir"/sandbox_profiles
sandbox_bundle="$out_dir"/sandbox_bundle
reversed_profiles="$out_dir"/reversed_profiles

echo "* ipsw file $ipsw"
ls -l "$ipsw"
file "$ipsw"
echo "* decrypted disk image file $decrypted"
ls -l "$decrypted"
file "$decrypted"
echo "* root filesystem image file $rootfs_img"
ls -l "$rootfs_img"
file "$rootfs_img"
echo "* filesystem archive file $fs_archive"
ls -l "$fs_archive"
file "$fs_archive"
echo "* sandboxd file $sandboxd"
ls -l "$sandboxd"
file "$sandboxd"
echo "* dyld_shared_cache folder $dyld_shared_cache"
ls -ld "$dyld_shared_cache"
ls "$dyld_shared_cache"
echo "* decrypted kernelcache file $kernelcache_decrypted"
ls -l "$kernelcache_decrypted"
file "$kernelcache_decrypted"
echo "* kernelcache file $kernelcache"
ls -l "$kernelcache"
file "$kernelcache"
echo "* sandbox extension file $sandbox_kext"
ls -l "$sandbox_kext"
file "$sandbox_kext"
echo "* sandbox operations file $sb_ops"
ls -l "$sb_ops"
file "$sb_ops"
echo "* sandbox profiles folder $sandbox_profiles"
ls -ld "$sandbox_profiles"
ls "$sandbox_profiles"
echo "* sandbox bundle file $sandbox_bundle"
ls -ld "$sandbox_bundle"
file "$sandbox_bundle"
echo "* reversed profiles folder $reversed_profiles"
ls -ld "$reversed_profiles"
ls "$reversed_profiles"
