#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <firmware-identifier>" 1>&2
    echo "" 1>&2
    echo "Argument is firmware identifier (e.g iPhone5,1_9.3_13E237)" 1>&2
    exit 1
fi

firmware_id="$1"

echo "* Change working directory to scripts/"
cd scripts
echo "* Extract sandbox profiles"
yes N | ./sandblaster_extract_operations "$firmware_id"
yes N | ./sandblaster_extract_profiles "$firmware_id"
echo "* Reverse sandbox profiles"
yes N | ./sandblaster_reverse_profiles "$firmware_id"
