#!/bin/bash

error()
{
    echo "[error] $1" 1>&2
}

debug()
{
    test ! -z "$DEBUG" && test "$DEBUG" -eq 1 && echo "[debug] $1" 1>&2
}

info()
{
    test ! -z "$INFO" && test "$INFO" -eq 1 && echo "[info] $1" 1>&2
}

usage()
{
    echo "$1" 1>&2
}

warn_if_error()
{
     test $? -eq 0 || error "Previous command ended with error. Turn on debugging and run manually to investigate." 1>&2
}

cd ..

if ! test -f config; then
    error "config file does not exist."
    error "Create one by copying config.sample and updating it."
    exit 1
fi

source config

if ! test -d "$STORE"; then
    error "Store folder ($STORE) does not exist."
    error "Create it and its subfolders from the config file."
    exit 1
fi

if ! test -d "$IPSW_STORE"; then
    error "Error: Firmware files folder ($IPSW_STORE) does not exist."
    error "Create it to store downloaded firmware images."
    exit 1
fi

if ! test -d "$OUT_STORE"; then
    error "Error: Output folder ($OUT_STORE) does not exist."
    error "Create it to store temporary processed/unpacked data."
    exit 1
fi

VFDECRYPT=tools/vfdecrypt/vfdecrypt
XPWN=tools/xpwn/builddir/ipsw-patch/xpwntool
LZSSDEC=tools/lzssdec/lzssdec
DYLD_EXTRACTOR=tools/dyld/dsc_extractor
if [[ "$OSTYPE" == linux* ]]; then
    JOKER=tools/joker/joker.ELF64
elif [[ "$OSTYPE" == darwin* ]]; then
    JOKER=tools/joker/joker.universal
fi
FW_METADATA_DIR=firmware-metadata

if ! test -f "$VFDECRYPT"; then
    error "Error: vfdecrypt executable does not exist at $VFDECRYPT"
    error "Make sure you compiled it."
    exit 1
fi

if ! test -f "$XPWN"; then
    error "Error: xpwntool executable does not exist at $XPWN"
    error "Make sure you compiled it."
    exit 1
fi

if ! test -f "$LZSSDEC"; then
    error "Error: lzssdec executable does not exist at $LZSSDEC"
    error "Make sure you compiled it."
    exit 1
fi

if ! test -f "$DYLD_EXTRACTOR"; then
    error "Error: dsc_extractor executable does not exist at $DYLD_EXTRACTOR"
    exit 1
fi

if ! test -f "$JOKER"; then
    error "Error: joker executable does not exist at $JOKER"
    exit 1
fi

if test $# -ne 1; then
    usage "Usage: $0 <firmware-identifier>"
    usage ""
    usage "Argument is firmware identifier (e.g iPhone5,1_9.3_13E237)"
    exit 1
fi

cd scripts/

base="$1"
metadata=../"$FW_METADATA_DIR/$base"
if ! test -f "$metadata"; then
    error "There is no configuration file in $FW_METADATA_DIR for identifier $base"
    error "Argument is firmware identifier (e.g iPhone5,1_9.3_13E237)"
    exit 1
fi

VFDECRYPT=../"$VFDECRYPT"
XPWN=../"$XPWN"
LZSSDEC=../"$LZSSDEC"
DYLD_EXTRACTOR=../"$DYLD_EXTRACTOR"
JOKER=../"$JOKER"
FW_METADATA_DIR=../"$FW_METADATA_DIR"

if [[ "$STORE" != /* ]]; then
    STORE=../"$STORE"
fi
if [[ "$IPSW_STORE" != /* ]]; then
    IPSW_STORE=../"$IPSW_STORE"
fi
if [[ "$OUT_STORE" != /* ]]; then
    OUT_STORE=../"$OUT_STORE"
fi

if [[ "$MOUNT_DIR" != /* ]]; then
    MOUNT_DIR=../"$MOUNT_DIR"
fi

out_dir="$OUT_STORE"/"$base"
ipsw="$IPSW_STORE"/"$base"_Restore.ipsw

if_no_exit()
{
    echo -en "$1 Do you want to continue?[y/N] "
    read -n 1 -r
    if [[ "$REPLY" =~ ^[Nn]$ || "$REPLY" == "" ]]; then
        echo "Not continuing."
        exit 0
    fi
    echo "Continuing ..."
}
