#!/bin/bash

source common

dmg=$(ls -S "$out_dir" | grep '^[0-9]\{3\}-[0-9]\+-[0-9]\{3\}.dmg' 2> /dev/null | head -n 1)
if ! test -f "$out_dir"/"$dmg"; then
    error "There is no .dmg file in $out_dir"
    error "Folder $out_dir doesn't store contents of an unpacked .ipsw file."
    exit 1
fi

if test -f "$out_dir"/decrypted.dmg; then
    if_no_exit "Decrypted image file $out_dir/decrypted.dmg already exists, a previous decryption may have already taken place."
fi

rootfs_key=$(cat "$metadata" | grep '^rootfs_key:' | sed 's/^[^:]*://' | tr -d ' ')

debug "Change working directory to bin/"
cd ../bin
debug "./decrypt_fs $out_dir/$dmg $rootfs_key"
./decrypt_fs "$out_dir"/"$dmg" "$rootfs_key"
