#!/bin/bash

source common

url=$(cat "$metadata" | grep '^firmware_download_url:' | sed 's/^[^:]*://' | tr -d ' ')
if test -z "$url"; then
    echo "No download URL in $metadata" 1>&2
    exit 1
fi

if test -f "$ipsw"; then
    if_no_exit "Firmware file already exists at $ipsw." 1>&2
fi

echo "Downloading firmware image file from $url ..."
wget "$url" -O "$ipsw"
