#!/bin/bash

source common

if [[ $OSTYPE != darwin* ]]; then
    error "No support for extracting the dyld shared cache on the $OSTYPE platform."
    exit 1
fi

mount_point=$(realpath "$MOUNT_DIR"/ios/"$base")
if ! mount | grep -qs "$mount_point"; then
    error "No volume is mounted in $mount_point"
    exit 1
fi

path_to_dyld_shared_cache=/System/Library/Caches/com.apple.dyld
paths=("$mount_point"/"$path_to_dyld_shared_cache"/dyld_shared_cache_*)
if test "${#paths[@]}" -eq 0; then
    error "There is no dyld_shared_cache file ($path_to_dyld_shared_cache) in $mount_point"
    exit 1
elif test "${#paths[@]}" -eq 1; then
    src=${paths[0]}
else
    src=${paths[0]}
    info "Multiple shared cache files, going for the first one: $src"
fi

dest="$out_dir"/dyld_shared_cache
if test -d "$dest"; then
    if_no_exit "Library extraction folder $dest already exists, a previous copying has probably taken place."
else
    mkdir "$out_dir"/dyld_shared_cache/
fi

debug "Change working directory to bin/"
cd ../bin
debug "./extract_dyld_shared_cache $src $dest"
./extract_dyld_shared_cache "$src" "$dest"
