#!/bin/bash

source common

if test $UID -ne 0; then
    error "You need to be root to run this script."
    exit 1
fi

mount_point=$(realpath "$MOUNT_DIR"/ios/"$base")
if ! mount | grep -qs "$mount_point"; then
    error "No volume is mounted in $mount_point"
    exit 1
fi

fs_archive="$out_dir"/fs.tar.gz
if test -f "$fs_archive"; then
    if_no_exit "Filesystem archive file $fs_archive already exists, a previous archiving has probably taken place."
fi

debug "Packing filesystem from $mount_point to $fs_archive ..."
debug "tar -C $mount_point -czf $fs_archive ."
tar -C "$mount_point" -czf "$fs_archive" . > /dev/null 2>&1
warn_if_error
