#!/bin/bash

source common

t=${base%_*}
version=${t##*_}
major=${version%%.*}

if test "$major" -lt 9; then
    binary_file="$out_dir"/sandboxd
    if ! test -f "$binary_file"; then
        error "There is no sandboxd file in $out_dir"
        exit 1
    fi

    dest="$out_dir"/sandbox_profiles
    if test -d "$dest"; then
        if_no_exit "Sandbox profiles folder $dest already exists. Extraction has likely happened previously."
    fi
    mkdir -p "$dest"
else
    binary_file="$out_dir"/com.apple.security.sandbox.kext
    if ! test -f "$binary_file"; then
        error "There is no com.apple.security.sandbox.kext file in $out_dir"
        exit 1
    fi

    dest="$out_dir"/sandbox_bundle
    if test -f "$dest"; then
        if_no_exit "Sandbox profiles bundle $dest already exists. Extraction has likely happened previously."
    fi
fi

if [[ $OSTYPE != darwin* ]]; then
    error "No support for extracting sandbox profiles on the $OSTYPE platform."
    exit 1
fi

if [[ "$out_dir" != /* ]]; then
    out_dir=../../"$out_dir"
fi

if [[ "$binary_file" != /* ]]; then
    binary_file=../../"$binary_file"
fi

debug "Change working directory to ../tools/sandblaster/helpers/"
cd ../tools/sandblaster/helpers/
debug "./extract_sandbox_data.py -O . "$binary_file" "$version""
./extract_sandbox_data.py -O . "$binary_file" "$version" 2> /dev/null

# old sandblaster helper scripts created sandbox_bundle in $out_dir
mv sandbox_bundle "$out_dir"
warn_if_error
